# Generated by Django 5.0.6 on 2024-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_end_time_alter_answer_is_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdetail',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
